/**
 * GENERATED by scripts/extract-factory-data.mjs — do not edit by hand.
 *
 * Turret-factory recipes and good prices lifted from the game's own Lua:
 *   data/scripts/lib/{goodsindex,turretingredients}.lua
 * for both the base game and the HET mod (workshop 445220/1821043731).
 *
 * INVESTMENT[type][stat] is the summed investFactor for a fully-invested turret,
 * i.e. the stat ends up multiplied by (1 + that value).
 */

/** Base price per unit of each good used in a turret recipe. */
export const GOOD_PRICE = {
  "Aluminium": 200,
  "Aluminum": 200,
  "Ammunition M": 422,
  "Ammunition S": 422,
  "Antigrav Generator": 71632,
  "Conductor": 168,
  "Copper": 350,
  "Crystal": 190,
  "Drill": 20443,
  "Electro Magnet": 483,
  "Electromagnetic Charge": 13985,
  "Energy Cell": 50,
  "Energy Container": 1087,
  "Energy Inverter": 1277,
  "Energy Tube": 2895,
  "Explosive Charge": 1423,
  "Force Generator": 49576,
  "Fuel": 1232,
  "Gauss Rail": 7735,
  "Glass": 182,
  "Gold": 600,
  "High Capacity Lens": 4689,
  "High Pressure Tube": 1650,
  "Industrial Tesla Coil": 10314,
  "Laser Compressor": 6577,
  "Laser Head": 4690,
  "Laser Modulator": 16742,
  "Lead": 200,
  "Military Tesla Coil": 10314,
  "Mining Robot": 145977,
  "Nanobot": 1338,
  "Nitrogen": 40,
  "Plasma Cell": 174,
  "Power Unit": 1211,
  "Rocket": 11250,
  "Servo": 1387,
  "Steel": 277,
  "Steel Tube": 704,
  "Targeting Card": 11873,
  "Targeting System": 29674,
  "Transformator": 209,
  "Turbine": 16729,
  "Warhead": 5630,
  "Wire": 95,
  "Zinc": 250
};

/** Vanilla recipes, keyed by WeaponType name. */
export const VANILLA_RECIPE = {
  "ChainGun": [
    {
      "name": "Servo",
      "amount": 15,
      "investable": 10,
      "minimum": 3,
      "rarityFactor": 0.75,
      "weaponStat": "fireRate",
      "investFactor": 0.3,
      "changeType": "Percentage"
    },
    {
      "name": "Steel Tube",
      "amount": 6,
      "investable": 7,
      "weaponStat": "reach",
      "investFactor": 0.4,
      "changeType": "Percentage"
    },
    {
      "name": "Ammunition S",
      "amount": 5,
      "investable": 10,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.4,
      "changeType": "Percentage"
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    },
    {
      "name": "Aluminum",
      "amount": 7,
      "investable": 5,
      "minimum": 3
    },
    {
      "name": "Lead",
      "amount": 10,
      "investable": 10,
      "minimum": 1
    }
  ],
  "PointDefenseChainGun": [
    {
      "name": "Servo",
      "amount": 17,
      "investable": 8,
      "minimum": 10,
      "rarityFactor": 0.75,
      "weaponStat": "fireRate",
      "investFactor": 0.3,
      "changeType": "Percentage"
    },
    {
      "name": "Steel Tube",
      "amount": 8,
      "investable": 5,
      "weaponStat": "reach",
      "investFactor": 0.4,
      "changeType": "Percentage"
    },
    {
      "name": "Ammunition S",
      "amount": 5,
      "investable": 5,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.4,
      "changeType": "Percentage"
    },
    {
      "name": "Steel",
      "amount": 3,
      "investable": 7,
      "minimum": 3
    },
    {
      "name": "Aluminum",
      "amount": 7,
      "investable": 5,
      "minimum": 3
    },
    {
      "name": "Lead",
      "amount": 10,
      "investable": 10,
      "minimum": 1
    }
  ],
  "Bolter": [
    {
      "name": "Servo",
      "amount": 15,
      "investable": 8,
      "minimum": 5,
      "rarityFactor": 0.75,
      "weaponStat": "fireRate",
      "investFactor": 1,
      "changeType": "Percentage"
    },
    {
      "name": "High Pressure Tube",
      "amount": 1,
      "investable": 3,
      "weaponStat": "reach",
      "investFactor": 0.4,
      "changeType": "Percentage"
    },
    {
      "name": "Ammunition M",
      "amount": 5,
      "investable": 10,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.1,
      "changeType": "Percentage"
    },
    {
      "name": "Explosive Charge",
      "amount": 2,
      "investable": 4,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.3,
      "changeType": "Percentage"
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    },
    {
      "name": "Aluminum",
      "amount": 7,
      "investable": 5,
      "minimum": 3
    }
  ],
  "Laser": [
    {
      "name": "Laser Head",
      "amount": 4,
      "investable": 4,
      "weaponStat": "damage",
      "investFactor": 0.1,
      "changeType": "Percentage"
    },
    {
      "name": "Laser Compressor",
      "amount": 2,
      "investable": 2,
      "weaponStat": "damage",
      "investFactor": 0.3,
      "changeType": "Percentage"
    },
    {
      "name": "High Capacity Lens",
      "amount": 2,
      "investable": 4,
      "weaponStat": "reach",
      "investFactor": 1,
      "changeType": "Percentage"
    },
    {
      "name": "Laser Modulator",
      "amount": 2,
      "investable": 4,
      "minimum": 2
    },
    {
      "name": "Power Unit",
      "amount": 5,
      "investable": 3,
      "minimum": 3,
      "turretStat": "maxHeat",
      "investFactor": 0.75,
      "changeType": "Percentage"
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    },
    {
      "name": "Crystal",
      "amount": 2,
      "investable": 10,
      "minimum": 1
    }
  ],
  "PointDefenseLaser": [
    {
      "name": "Servo",
      "amount": 17,
      "investable": 8,
      "minimum": 10,
      "rarityFactor": 0.75,
      "weaponStat": "fireRate",
      "investFactor": 0.3,
      "changeType": "Percentage"
    },
    {
      "name": "Laser Head",
      "amount": 2,
      "investable": 2,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.1,
      "changeType": "Percentage"
    },
    {
      "name": "Laser Compressor",
      "amount": 2,
      "investable": 1,
      "weaponStat": "damage",
      "investFactor": 0.3,
      "changeType": "Percentage"
    },
    {
      "name": "High Capacity Lens",
      "amount": 2,
      "investable": 4,
      "weaponStat": "reach",
      "investFactor": 1,
      "changeType": "Percentage"
    },
    {
      "name": "Laser Modulator",
      "amount": 2,
      "investable": 4
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    },
    {
      "name": "Crystal",
      "amount": 2,
      "investable": 10,
      "minimum": 1
    }
  ],
  "PlasmaGun": [
    {
      "name": "Plasma Cell",
      "amount": 8,
      "investable": 4,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.4,
      "changeType": "Percentage"
    },
    {
      "name": "Energy Tube",
      "amount": 2,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "reach",
      "investFactor": 0.4,
      "changeType": "Percentage"
    },
    {
      "name": "Conductor",
      "amount": 5,
      "investable": 6,
      "minimum": 1
    },
    {
      "name": "Energy Container",
      "amount": 5,
      "investable": 6,
      "minimum": 1
    },
    {
      "name": "Power Unit",
      "amount": 5,
      "investable": 3,
      "minimum": 3,
      "turretStat": "maxHeat",
      "investFactor": 0.75,
      "changeType": "Percentage"
    },
    {
      "name": "Steel",
      "amount": 4,
      "investable": 10,
      "minimum": 3
    },
    {
      "name": "Crystal",
      "amount": 2,
      "investable": 10,
      "minimum": 1
    }
  ],
  "Cannon": [
    {
      "name": "Servo",
      "amount": 15,
      "investable": 10,
      "minimum": 5,
      "weaponStat": "fireRate",
      "investFactor": 1,
      "changeType": "Percentage"
    },
    {
      "name": "Warhead",
      "amount": 5,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.4,
      "changeType": "Percentage"
    },
    {
      "name": "High Pressure Tube",
      "amount": 2,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "reach",
      "investFactor": 0.4,
      "changeType": "Percentage"
    },
    {
      "name": "Explosive Charge",
      "amount": 2,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.2,
      "changeType": "Percentage"
    },
    {
      "name": "Steel",
      "amount": 8,
      "investable": 10,
      "minimum": 3
    },
    {
      "name": "Wire",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    }
  ],
  "RocketLauncher": [
    {
      "name": "Servo",
      "amount": 15,
      "investable": 10,
      "minimum": 5,
      "weaponStat": "fireRate",
      "investFactor": 1,
      "changeType": "Percentage"
    },
    {
      "name": "Rocket",
      "amount": 5,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.4,
      "changeType": "Percentage"
    },
    {
      "name": "High Pressure Tube",
      "amount": 2,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "reach",
      "investFactor": 0.4,
      "changeType": "Percentage"
    },
    {
      "name": "Fuel",
      "amount": 2,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "reach",
      "investFactor": 0.5,
      "changeType": "Percentage"
    },
    {
      "name": "Targeting Card",
      "amount": 5,
      "investable": 5,
      "minimum": 0,
      "weaponStat": "seeker",
      "investFactor": 1,
      "changeType": "Flat"
    },
    {
      "name": "Steel",
      "amount": 8,
      "investable": 10,
      "minimum": 3
    },
    {
      "name": "Wire",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    }
  ],
  "RailGun": [
    {
      "name": "Servo",
      "amount": 15,
      "investable": 10,
      "minimum": 6,
      "weaponStat": "fireRate",
      "investFactor": 1,
      "changeType": "Percentage"
    },
    {
      "name": "Electromagnetic Charge",
      "amount": 5,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.3,
      "changeType": "Percentage"
    },
    {
      "name": "Electro Magnet",
      "amount": 8,
      "investable": 10,
      "minimum": 3,
      "weaponStat": "reach",
      "investFactor": 0.3,
      "changeType": "Percentage"
    },
    {
      "name": "Gauss Rail",
      "amount": 5,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.3,
      "changeType": "Percentage"
    },
    {
      "name": "High Pressure Tube",
      "amount": 2,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "reach",
      "investFactor": 0.3,
      "changeType": "Percentage"
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    },
    {
      "name": "Copper",
      "amount": 2,
      "investable": 10,
      "minimum": 1
    }
  ],
  "RepairBeam": [
    {
      "name": "Nanobot",
      "amount": 5,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "hullRepair",
      "investFactor": 0.4,
      "changeType": "Percentage"
    },
    {
      "name": "Transformator",
      "amount": 2,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "shieldRepair",
      "investFactor": 0.4,
      "changeType": "Percentage"
    },
    {
      "name": "Laser Modulator",
      "amount": 2,
      "investable": 5,
      "minimum": 0,
      "weaponStat": "reach",
      "investFactor": 0.75,
      "changeType": "Percentage"
    },
    {
      "name": "Conductor",
      "amount": 2,
      "investable": 6,
      "minimum": 0,
      "turretStat": "energyIncreasePerSecond",
      "investFactor": -0.5,
      "changeType": "Percentage"
    },
    {
      "name": "Gold",
      "amount": 3,
      "investable": 10,
      "minimum": 1
    },
    {
      "name": "Steel",
      "amount": 8,
      "investable": 10,
      "minimum": 3
    }
  ],
  "MiningLaser": [
    {
      "name": "Laser Compressor",
      "amount": 5,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.075,
      "changeType": "Percentage"
    },
    {
      "name": "Laser Modulator",
      "amount": 2,
      "investable": 4,
      "minimum": 0,
      "weaponStat": "stoneRefinedEfficiency",
      "investFactor": 0.075,
      "changeType": "Flat"
    },
    {
      "name": "High Capacity Lens",
      "amount": 2,
      "investable": 6,
      "minimum": 0,
      "weaponStat": "reach",
      "investFactor": 1,
      "changeType": "Percentage"
    },
    {
      "name": "Conductor",
      "amount": 5,
      "investable": 6,
      "minimum": 2
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    }
  ],
  "SalvagingLaser": [
    {
      "name": "Laser Compressor",
      "amount": 5,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.4,
      "changeType": "Percentage"
    },
    {
      "name": "Laser Modulator",
      "amount": 2,
      "investable": 4,
      "minimum": 0,
      "weaponStat": "metalRefinedEfficiency",
      "investFactor": 0.075,
      "changeType": "Flat"
    },
    {
      "name": "High Capacity Lens",
      "amount": 2,
      "investable": 6,
      "minimum": 0,
      "weaponStat": "reach",
      "investFactor": 1,
      "changeType": "Percentage"
    },
    {
      "name": "Conductor",
      "amount": 5,
      "investable": 6,
      "minimum": 2
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    }
  ],
  "RawMiningLaser": [
    {
      "name": "Laser Compressor",
      "amount": 5,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.075,
      "changeType": "Percentage"
    },
    {
      "name": "Laser Modulator",
      "amount": 2,
      "investable": 4,
      "minimum": 0,
      "weaponStat": "stoneRawEfficiency",
      "investFactor": 0.075,
      "changeType": "Flat"
    },
    {
      "name": "High Capacity Lens",
      "amount": 2,
      "investable": 6,
      "minimum": 0,
      "weaponStat": "reach",
      "investFactor": 1,
      "changeType": "Percentage"
    },
    {
      "name": "Conductor",
      "amount": 5,
      "investable": 6,
      "minimum": 2
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    }
  ],
  "RawSalvagingLaser": [
    {
      "name": "Laser Compressor",
      "amount": 5,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.4,
      "changeType": "Percentage"
    },
    {
      "name": "Laser Modulator",
      "amount": 2,
      "investable": 4,
      "minimum": 0,
      "weaponStat": "metalRawEfficiency",
      "investFactor": 0.075,
      "changeType": "Flat"
    },
    {
      "name": "High Capacity Lens",
      "amount": 2,
      "investable": 6,
      "minimum": 0,
      "weaponStat": "reach",
      "investFactor": 1,
      "changeType": "Percentage"
    },
    {
      "name": "Conductor",
      "amount": 5,
      "investable": 6,
      "minimum": 2
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    }
  ],
  "ForceGun": [
    {
      "name": "Force Generator",
      "amount": 5,
      "investable": 3,
      "minimum": 1,
      "weaponStat": "holdingForce",
      "investFactor": 0.4,
      "changeType": "Percentage"
    },
    {
      "name": "Energy Tube",
      "amount": 2,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "reach",
      "investFactor": 1,
      "changeType": "Percentage"
    },
    {
      "name": "Conductor",
      "amount": 10,
      "investable": 6,
      "minimum": 2
    },
    {
      "name": "Steel",
      "amount": 7,
      "investable": 10,
      "minimum": 3
    },
    {
      "name": "Zinc",
      "amount": 3,
      "investable": 10,
      "minimum": 3
    }
  ],
  "TeslaGun": [
    {
      "name": "Industrial Tesla Coil",
      "amount": 5,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.4,
      "changeType": "Percentage"
    },
    {
      "name": "Electromagnetic Charge",
      "amount": 2,
      "investable": 4,
      "minimum": 1,
      "weaponStat": "reach",
      "investFactor": 0.3,
      "changeType": "Percentage"
    },
    {
      "name": "Energy Inverter",
      "amount": 2,
      "investable": 4,
      "minimum": 1
    },
    {
      "name": "Conductor",
      "amount": 5,
      "investable": 6,
      "minimum": 2
    },
    {
      "name": "Power Unit",
      "amount": 5,
      "investable": 3,
      "minimum": 3,
      "turretStat": "maxHeat",
      "investFactor": 0.75,
      "changeType": "Percentage"
    },
    {
      "name": "Copper",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    },
    {
      "name": "Energy Cell",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    }
  ],
  "LightningGun": [
    {
      "name": "Military Tesla Coil",
      "amount": 5,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.45,
      "changeType": "Percentage"
    },
    {
      "name": "High Capacity Lens",
      "amount": 2,
      "investable": 4,
      "minimum": 1,
      "weaponStat": "reach",
      "investFactor": 0.2,
      "changeType": "Percentage"
    },
    {
      "name": "Electromagnetic Charge",
      "amount": 2,
      "investable": 4,
      "minimum": 1
    },
    {
      "name": "Conductor",
      "amount": 5,
      "investable": 6,
      "minimum": 2
    },
    {
      "name": "Power Unit",
      "amount": 5,
      "investable": 3,
      "minimum": 3,
      "turretStat": "maxHeat",
      "investFactor": 0.75,
      "changeType": "Percentage"
    },
    {
      "name": "Copper",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    },
    {
      "name": "Energy Cell",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    }
  ],
  "PulseCannon": [
    {
      "name": "Servo",
      "amount": 8,
      "investable": 8,
      "minimum": 3,
      "rarityFactor": 0.75,
      "weaponStat": "fireRate",
      "investFactor": 0.3,
      "changeType": "Percentage"
    },
    {
      "name": "Steel Tube",
      "amount": 6,
      "investable": 7,
      "weaponStat": "reach",
      "investFactor": 0.4,
      "changeType": "Percentage"
    },
    {
      "name": "Ammunition S",
      "amount": 5,
      "investable": 10,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.4,
      "changeType": "Percentage"
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 10,
      "minimum": 4
    },
    {
      "name": "Copper",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    },
    {
      "name": "Energy Cell",
      "amount": 3,
      "investable": 5,
      "minimum": 2
    }
  ],
  "AntiFighter": [
    {
      "name": "Servo",
      "amount": 17,
      "investable": 8,
      "minimum": 10,
      "rarityFactor": 0.75,
      "weaponStat": "fireRate",
      "investFactor": 0.3,
      "changeType": "Percentage"
    },
    {
      "name": "High Pressure Tube",
      "amount": 1,
      "investable": 3,
      "weaponStat": "reach",
      "investFactor": 0.5,
      "changeType": "Percentage"
    },
    {
      "name": "Ammunition M",
      "amount": 5,
      "investable": 5,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.2,
      "changeType": "Percentage"
    },
    {
      "name": "Explosive Charge",
      "amount": 2,
      "investable": 4,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.4,
      "changeType": "Percentage"
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    },
    {
      "name": "Aluminum",
      "amount": 7,
      "investable": 5,
      "minimum": 3
    }
  ]
};

/** HET mod recipes, keyed by WeaponType name. */
export const HET_RECIPE = {
  "HETRepairBeam": [
    {
      "name": "Nanobot",
      "amount": 5,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "hullRepair"
    },
    {
      "name": "Transformator",
      "amount": 2,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "shieldRepair",
      "investFactor": 0.75
    },
    {
      "name": "Laser Modulator",
      "amount": 2,
      "investable": 5,
      "minimum": 0,
      "weaponStat": "reach",
      "investFactor": 0.75,
      "changeType": "Percentage"
    },
    {
      "name": "Conductor",
      "amount": 2,
      "investable": 6,
      "minimum": 0
    },
    {
      "name": "Gold",
      "amount": 3,
      "investable": 10,
      "minimum": 1
    },
    {
      "name": "Steel",
      "amount": 8,
      "investable": 10,
      "minimum": 3
    }
  ],
  "HETMiningLaser": [
    {
      "name": "Laser Compressor",
      "amount": 1,
      "investable": 1,
      "minimum": 1,
      "weaponStat": "damage"
    },
    {
      "name": "High Capacity Lens",
      "amount": 1,
      "investable": 2,
      "minimum": 1,
      "weaponStat": "reach",
      "investFactor": 2
    },
    {
      "name": "Conductor",
      "amount": 5,
      "investable": 6,
      "minimum": 7
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 15,
      "minimum": 3
    }
  ],
  "HETSalvagingLaser": [
    {
      "name": "Laser Compressor",
      "amount": 5,
      "investable": 6,
      "minimum": 5,
      "weaponStat": "damage"
    },
    {
      "name": "High Capacity Lens",
      "amount": 2,
      "investable": 6,
      "minimum": 5,
      "weaponStat": "reach",
      "investFactor": 2
    },
    {
      "name": "Conductor",
      "amount": 5,
      "investable": 6,
      "minimum": 8
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 20,
      "minimum": 3
    }
  ],
  "HETForceGun": [
    {
      "name": "Force Generator",
      "amount": 5,
      "investable": 3,
      "minimum": 1,
      "weaponStat": "otherForce",
      "investFactor": 1,
      "changeType": "Percentage"
    },
    {
      "name": "Energy Inverter",
      "amount": 2,
      "investable": 4,
      "minimum": 1,
      "weaponStat": "selfForce",
      "investFactor": 1,
      "changeType": "Percentage"
    },
    {
      "name": "Energy Tube",
      "amount": 2,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "reach",
      "investFactor": 2
    },
    {
      "name": "Conductor",
      "amount": 10,
      "investable": 6,
      "minimum": 2
    },
    {
      "name": "Steel",
      "amount": 7,
      "investable": 10,
      "minimum": 3
    },
    {
      "name": "Zinc",
      "amount": 3,
      "investable": 10,
      "minimum": 3
    }
  ],
  "HETBolter": [
    {
      "name": "High Pressure Tube",
      "amount": 1,
      "investable": 3,
      "weaponStat": "reach",
      "investFactor": 1.5
    },
    {
      "name": "Ammunition M",
      "amount": 5,
      "investable": 20,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.15
    },
    {
      "name": "Explosive Charge",
      "amount": 2,
      "investable": 20,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.15
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    },
    {
      "name": "Aluminium",
      "amount": 7,
      "investable": 5,
      "minimum": 3
    },
    {
      "name": "Copper",
      "amount": 10,
      "investable": 0,
      "minimum": 10
    },
    {
      "name": "Lead",
      "amount": 10,
      "investable": 10,
      "minimum": 1
    },
    {
      "name": "Conductor",
      "amount": 5,
      "investable": 0,
      "minimum": 5
    }
  ],
  "HETAntiFighter": [
    {
      "name": "High Pressure Tube",
      "amount": 1,
      "investable": 3,
      "weaponStat": "reach",
      "investFactor": 1.5
    },
    {
      "name": "Ammunition M",
      "amount": 5,
      "investable": 5,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.25
    },
    {
      "name": "Explosive Charge",
      "amount": 2,
      "investable": 4,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 1.5
    },
    {
      "name": "Rocket",
      "amount": 5,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "damage"
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    },
    {
      "name": "Aluminium",
      "amount": 7,
      "investable": 5,
      "minimum": 3
    },
    {
      "name": "Targeting Card",
      "amount": 5,
      "investable": 0,
      "minimum": 5,
      "weaponStat": "seeker",
      "investFactor": 1,
      "changeType": "Flat"
    }
  ],
  "HETRailGun": [
    {
      "name": "Electromagnetic Charge",
      "amount": 5,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.07
    },
    {
      "name": "Gauss Rail",
      "amount": 5,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.07
    },
    {
      "name": "Electro Magnet",
      "amount": 8,
      "investable": 10,
      "minimum": 3,
      "weaponStat": "reach",
      "investFactor": 0.1
    },
    {
      "name": "High Pressure Tube",
      "amount": 2,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "reach",
      "investFactor": 0.1
    },
    {
      "name": "Steel",
      "amount": 10,
      "investable": 0,
      "minimum": 10
    },
    {
      "name": "Copper",
      "amount": 10,
      "investable": 0,
      "minimum": 10
    },
    {
      "name": "Aluminium",
      "amount": 7,
      "investable": 0,
      "minimum": 7
    },
    {
      "name": "Conductor",
      "amount": 5,
      "investable": 0,
      "minimum": 5
    }
  ],
  "HETChainGun": [
    {
      "name": "Ammunition S",
      "amount": 5,
      "investable": 10,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.7
    },
    {
      "name": "Steel Tube",
      "amount": 6,
      "investable": 7,
      "weaponStat": "reach"
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    },
    {
      "name": "Aluminium",
      "amount": 7,
      "investable": 5,
      "minimum": 3
    },
    {
      "name": "Copper",
      "amount": 10,
      "investable": 0,
      "minimum": 10
    },
    {
      "name": "Lead",
      "amount": 10,
      "investable": 10,
      "minimum": 1
    },
    {
      "name": "Conductor",
      "amount": 5,
      "investable": 0,
      "minimum": 5
    }
  ],
  "HETFlamethrower": [
    {
      "name": "Explosive Charge",
      "amount": 2,
      "investable": 4,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.45
    },
    {
      "name": "High Pressure Tube",
      "amount": 2,
      "investable": 6,
      "minimum": 1
    },
    {
      "name": "Copper",
      "amount": 10,
      "investable": 0,
      "minimum": 10
    },
    {
      "name": "Fuel",
      "amount": 10,
      "investable": 6,
      "minimum": 4
    },
    {
      "name": "Turbine",
      "amount": 3,
      "investable": 4,
      "minimum": 1
    },
    {
      "name": "Nitrogen",
      "amount": 3,
      "investable": 6,
      "minimum": 3
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    }
  ],
  "HETLaser": [
    {
      "name": "Electro Magnet",
      "amount": 8,
      "investable": 10,
      "minimum": 3,
      "weaponStat": "reach",
      "investFactor": 0.1
    },
    {
      "name": "High Pressure Tube",
      "amount": 3,
      "investable": 6,
      "minimum": 3,
      "weaponStat": "reach",
      "investFactor": 0.1
    },
    {
      "name": "Laser Modulator",
      "amount": 6,
      "investable": 5,
      "minimum": 3,
      "weaponStat": "reach",
      "investFactor": 0.1,
      "changeType": "Percentage"
    },
    {
      "name": "Laser Compressor",
      "amount": 7,
      "investable": 7,
      "minimum": 1
    },
    {
      "name": "Laser Head",
      "amount": 8,
      "investable": 2,
      "minimum": 3
    },
    {
      "name": "Glass",
      "amount": 6,
      "investable": 3,
      "minimum": 3
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    }
  ],
  "HETRepairDropper": [
    {
      "name": "Nanobot",
      "amount": 5,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "hullRepair",
      "investFactor": 205,
      "changeType": "Percentage"
    },
    {
      "name": "Transformator",
      "amount": 5,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "shieldRepair",
      "investFactor": 20000,
      "changeType": "Flat"
    },
    {
      "name": "Electro Magnet",
      "amount": 8,
      "investable": 10,
      "minimum": 3,
      "weaponStat": "reach",
      "investFactor": 1.5
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    },
    {
      "name": "Aluminium",
      "amount": 7,
      "investable": 5,
      "minimum": 3
    },
    {
      "name": "Targeting Card",
      "amount": 5,
      "investable": 0,
      "minimum": 5,
      "weaponStat": "seeker",
      "investFactor": 1,
      "changeType": "Flat"
    }
  ],
  "HETTopedoKiller": [
    {
      "name": "Laser Modulator",
      "amount": 5,
      "investable": 1,
      "minimum": 2,
      "weaponStat": "reach",
      "investFactor": 0.55,
      "changeType": "Percentage"
    },
    {
      "name": "Laser Compressor",
      "amount": 3,
      "investable": 2,
      "minimum": 3
    },
    {
      "name": "Laser Head",
      "amount": 3,
      "investable": 2,
      "minimum": 2
    },
    {
      "name": "Glass",
      "amount": 2,
      "investable": 1,
      "minimum": 4
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 6,
      "minimum": 3
    },
    {
      "name": "Crystal",
      "amount": 2,
      "investable": 10,
      "minimum": 2
    }
  ],
  "HETPulseShotgun": [
    {
      "name": "Ammunition S",
      "amount": 5,
      "investable": 10,
      "minimum": 2,
      "weaponStat": "damage",
      "investFactor": 0.7
    },
    {
      "name": "High Pressure Tube",
      "amount": 3,
      "investable": 6,
      "minimum": 3,
      "weaponStat": "reach",
      "investFactor": 0.05
    },
    {
      "name": "Conductor",
      "amount": 5,
      "investable": 6,
      "minimum": 4
    },
    {
      "name": "Copper",
      "amount": 10,
      "investable": 7,
      "minimum": 3
    },
    {
      "name": "Aluminium",
      "amount": 7,
      "investable": 5,
      "minimum": 3
    },
    {
      "name": "Lead",
      "amount": 10,
      "investable": 10,
      "minimum": 1
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 6,
      "minimum": 3
    }
  ],
  "HETSwarmMissiles": [
    {
      "name": "High Pressure Tube",
      "amount": 1,
      "investable": 3,
      "minimum": 3,
      "weaponStat": "reach",
      "investFactor": 1.5
    },
    {
      "name": "Explosive Charge",
      "amount": 1,
      "investable": 1,
      "minimum": 4,
      "weaponStat": "damage",
      "investFactor": 0.25
    },
    {
      "name": "Rocket",
      "amount": 1,
      "investable": 1,
      "minimum": 2,
      "weaponStat": "damage"
    },
    {
      "name": "Conductor",
      "amount": 5,
      "investable": 6,
      "minimum": 4
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    },
    {
      "name": "Aluminium",
      "amount": 7,
      "investable": 5,
      "minimum": 3
    },
    {
      "name": "Targeting Card",
      "amount": 5,
      "investable": 0,
      "minimum": 5,
      "weaponStat": "seeker",
      "investFactor": 1,
      "changeType": "Flat"
    }
  ],
  "HETRefinementDropper": [
    {
      "name": "Nanobot",
      "amount": 2,
      "investable": 4,
      "minimum": 2
    },
    {
      "name": "Laser Compressor",
      "amount": 2,
      "investable": 4,
      "minimum": 3
    },
    {
      "name": "Antigrav Generator",
      "amount": 4,
      "investable": 8,
      "minimum": 4
    },
    {
      "name": "Drill",
      "amount": 4,
      "investable": 9,
      "minimum": 5
    },
    {
      "name": "Mining Robot",
      "amount": 3,
      "investable": 6,
      "minimum": 3
    },
    {
      "name": "Conductor",
      "amount": 5,
      "investable": 6,
      "minimum": 2
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    }
  ],
  "HETRMHammerHead": [
    {
      "name": "Laser Compressor",
      "amount": 3,
      "investable": 4,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.07
    },
    {
      "name": "High Capacity Lens",
      "amount": 2,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "reach",
      "investFactor": 1
    },
    {
      "name": "Conductor",
      "amount": 5,
      "investable": 6,
      "minimum": 2
    },
    {
      "name": "Aluminium",
      "amount": 2,
      "investable": 5,
      "minimum": 3
    },
    {
      "name": "High Pressure Tube",
      "amount": 2,
      "investable": 5,
      "minimum": 3
    },
    {
      "name": "Industrial Tesla Coil",
      "amount": 2,
      "investable": 5,
      "minimum": 3
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    }
  ],
  "HETRSHammerHead": [
    {
      "name": "Laser Compressor",
      "amount": 3,
      "investable": 4,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.07
    },
    {
      "name": "High Capacity Lens",
      "amount": 2,
      "investable": 6,
      "minimum": 0,
      "weaponStat": "reach",
      "investFactor": 1
    },
    {
      "name": "Conductor",
      "amount": 5,
      "investable": 6,
      "minimum": 2
    },
    {
      "name": "Aluminium",
      "amount": 2,
      "investable": 5,
      "minimum": 3
    },
    {
      "name": "High Pressure Tube",
      "amount": 2,
      "investable": 5,
      "minimum": 3
    },
    {
      "name": "Industrial Tesla Coil",
      "amount": 2,
      "investable": 5,
      "minimum": 3
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    }
  ],
  "HETGatlingPlasma": [
    {
      "name": "Plasma Cell",
      "amount": 8,
      "investable": 4,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.07
    },
    {
      "name": "Energy Tube",
      "amount": 2,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "reach"
    },
    {
      "name": "Conductor",
      "amount": 5,
      "investable": 6,
      "minimum": 1
    },
    {
      "name": "Energy Container",
      "amount": 5,
      "investable": 6,
      "minimum": 1
    },
    {
      "name": "Power Unit",
      "amount": 5,
      "investable": 3,
      "minimum": 3
    },
    {
      "name": "Steel",
      "amount": 4,
      "investable": 10,
      "minimum": 3
    },
    {
      "name": "Crystal",
      "amount": 2,
      "investable": 10,
      "minimum": 1
    }
  ],
  "HETCannon": [
    {
      "name": "Explosive Charge",
      "amount": 2,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.4
    },
    {
      "name": "Plasma Cell",
      "amount": 3,
      "investable": 7,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.35
    },
    {
      "name": "Energy Tube",
      "amount": 2,
      "investable": 3,
      "minimum": 1,
      "weaponStat": "reach"
    },
    {
      "name": "High Pressure Tube",
      "amount": 1,
      "investable": 3,
      "weaponStat": "reach",
      "investFactor": 0.5
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 10,
      "minimum": 3
    },
    {
      "name": "Energy Container",
      "amount": 5,
      "investable": 6,
      "minimum": 1
    },
    {
      "name": "Power Unit",
      "amount": 5,
      "investable": 3,
      "minimum": 3
    },
    {
      "name": "Conductor",
      "amount": 5,
      "investable": 0,
      "minimum": 5
    }
  ],
  "HETInpulse": [
    {
      "name": "Force Generator",
      "amount": 5,
      "investable": 1,
      "minimum": 1
    },
    {
      "name": "Conductor",
      "amount": 5,
      "investable": 1,
      "minimum": 5
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 1,
      "minimum": 3
    },
    {
      "name": "Copper",
      "amount": 10,
      "investable": 1,
      "minimum": 3
    },
    {
      "name": "Aluminium",
      "amount": 7,
      "investable": 1,
      "minimum": 3
    },
    {
      "name": "Lead",
      "amount": 10,
      "investable": 1,
      "minimum": 1
    },
    {
      "name": "Targeting Card",
      "amount": 5,
      "investable": 0,
      "minimum": 5
    }
  ],
  "HETTeslaGun": [
    {
      "name": "Industrial Tesla Coil",
      "amount": 2,
      "investable": 5,
      "minimum": 3,
      "weaponStat": "damage",
      "investFactor": 0.4
    },
    {
      "name": "Force Generator",
      "amount": 5,
      "investable": 4,
      "minimum": 1,
      "weaponStat": "otherForce",
      "investFactor": 1,
      "changeType": "Percentage"
    },
    {
      "name": "High Pressure Tube",
      "amount": 2,
      "investable": 5,
      "minimum": 3
    },
    {
      "name": "Conductor",
      "amount": 5,
      "investable": 3,
      "minimum": 5
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 2,
      "minimum": 3
    },
    {
      "name": "Aluminium",
      "amount": 7,
      "investable": 5,
      "minimum": 3
    }
  ],
  "HETInterceptor": [
    {
      "name": "Explosive Charge",
      "amount": 2,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.4
    },
    {
      "name": "Ammunition M",
      "amount": 5,
      "investable": 3,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.7
    },
    {
      "name": "High Pressure Tube",
      "amount": 1,
      "investable": 3,
      "weaponStat": "reach",
      "investFactor": 0.5
    },
    {
      "name": "Steel",
      "amount": 5,
      "investable": 5,
      "minimum": 3
    },
    {
      "name": "Aluminium",
      "amount": 7,
      "investable": 4,
      "minimum": 3
    }
  ],
  "HETLRL40160": [
    {
      "name": "Nanobot",
      "amount": 5,
      "investable": 6,
      "minimum": 5,
      "weaponStat": "hullRepair",
      "investFactor": 0.75
    },
    {
      "name": "Laser Modulator",
      "amount": 2,
      "investable": 5,
      "minimum": 4,
      "weaponStat": "reach",
      "investFactor": 0.75,
      "changeType": "Percentage"
    },
    {
      "name": "Conductor",
      "amount": 2,
      "investable": 6,
      "minimum": 2
    },
    {
      "name": "Gold",
      "amount": 3,
      "investable": 10,
      "minimum": 4
    },
    {
      "name": "Steel",
      "amount": 8,
      "investable": 10,
      "minimum": 4
    }
  ],
  "HETPredatorCannon": [
    {
      "name": "Explosive Charge",
      "amount": 2,
      "investable": 4,
      "minimum": 3,
      "weaponStat": "damage",
      "investFactor": 0.45
    },
    {
      "name": "Ammunition M",
      "amount": 5,
      "investable": 3,
      "minimum": 3,
      "weaponStat": "damage",
      "investFactor": 0.45
    },
    {
      "name": "Transformator",
      "amount": 5,
      "investable": 6,
      "minimum": 6
    },
    {
      "name": "High Pressure Tube",
      "amount": 2,
      "investable": 6,
      "minimum": 2
    },
    {
      "name": "Copper",
      "amount": 10,
      "investable": 0,
      "minimum": 10
    },
    {
      "name": "Lead",
      "amount": 10,
      "investable": 5,
      "minimum": 3
    },
    {
      "name": "Steel",
      "amount": 8,
      "investable": 10,
      "minimum": 4
    }
  ],
  "HETCrawler": [
    {
      "name": "Explosive Charge",
      "amount": 2,
      "investable": 4,
      "minimum": 3,
      "weaponStat": "damage",
      "investFactor": 0.45
    },
    {
      "name": "High Pressure Tube",
      "amount": 2,
      "investable": 6,
      "minimum": 2
    },
    {
      "name": "Conductor",
      "amount": 5,
      "investable": 3,
      "minimum": 5
    },
    {
      "name": "Copper",
      "amount": 10,
      "investable": 0,
      "minimum": 10
    },
    {
      "name": "Lead",
      "amount": 10,
      "investable": 5,
      "minimum": 3
    },
    {
      "name": "Steel",
      "amount": 8,
      "investable": 10,
      "minimum": 4
    },
    {
      "name": "Targeting Card",
      "amount": 5,
      "investable": 0,
      "minimum": 5
    }
  ],
  "HETClusters": [
    {
      "name": "Explosive Charge",
      "amount": 6,
      "investable": 5,
      "minimum": 4,
      "weaponStat": "damage",
      "investFactor": 0.45
    },
    {
      "name": "High Pressure Tube",
      "amount": 2,
      "investable": 6,
      "minimum": 2
    },
    {
      "name": "High Capacity Lens",
      "amount": 2,
      "investable": 6,
      "minimum": 0,
      "weaponStat": "reach",
      "investFactor": 0.25
    },
    {
      "name": "Conductor",
      "amount": 5,
      "investable": 3,
      "minimum": 5
    },
    {
      "name": "Copper",
      "amount": 10,
      "investable": 0,
      "minimum": 10
    },
    {
      "name": "Lead",
      "amount": 10,
      "investable": 5,
      "minimum": 3
    },
    {
      "name": "Steel",
      "amount": 8,
      "investable": 10,
      "minimum": 4
    },
    {
      "name": "Targeting Card",
      "amount": 5,
      "investable": 0,
      "minimum": 5
    }
  ],
  "HETADST": [
    {
      "name": "High Pressure Tube",
      "amount": 6,
      "investable": 5,
      "minimum": 4,
      "weaponStat": "damage",
      "investFactor": 0.45
    },
    {
      "name": "Ammunition M",
      "amount": 5,
      "investable": 3,
      "minimum": 3,
      "weaponStat": "damage",
      "investFactor": 0.45
    },
    {
      "name": "High Capacity Lens",
      "amount": 2,
      "investable": 6,
      "minimum": 0,
      "weaponStat": "reach",
      "investFactor": 0.25
    },
    {
      "name": "Conductor",
      "amount": 5,
      "investable": 3,
      "minimum": 5
    },
    {
      "name": "Copper",
      "amount": 10,
      "investable": 0,
      "minimum": 10
    },
    {
      "name": "Lead",
      "amount": 10,
      "investable": 5,
      "minimum": 3
    },
    {
      "name": "Steel",
      "amount": 8,
      "investable": 10,
      "minimum": 4
    }
  ],
  "HETLLTLT": [
    {
      "name": "Explosive Charge",
      "amount": 6,
      "investable": 5,
      "minimum": 4
    },
    {
      "name": "Rocket",
      "amount": 8,
      "investable": 12,
      "minimum": 4
    },
    {
      "name": "High Pressure Tube",
      "amount": 2,
      "investable": 6,
      "minimum": 2
    },
    {
      "name": "High Capacity Lens",
      "amount": 2,
      "investable": 6,
      "minimum": 0
    },
    {
      "name": "Conductor",
      "amount": 5,
      "investable": 3,
      "minimum": 5
    },
    {
      "name": "Laser Modulator",
      "amount": 2,
      "investable": 5,
      "minimum": 4
    },
    {
      "name": "Steel",
      "amount": 8,
      "investable": 10,
      "minimum": 4
    },
    {
      "name": "Targeting System",
      "amount": 2,
      "investable": 0,
      "minimum": 2,
      "turretStat": "automatic",
      "investFactor": 1,
      "changeType": "Flat"
    }
  ],
  "HETOphidian": [
    {
      "name": "Plasma Cell",
      "amount": 5,
      "investable": 4,
      "minimum": 1,
      "weaponStat": "damage",
      "investFactor": 0.07
    },
    {
      "name": "Energy Tube",
      "amount": 2,
      "investable": 6,
      "minimum": 1,
      "weaponStat": "reach"
    },
    {
      "name": "Conductor",
      "amount": 5,
      "investable": 6,
      "minimum": 1
    },
    {
      "name": "Energy Container",
      "amount": 4,
      "investable": 6,
      "minimum": 1
    },
    {
      "name": "Power Unit",
      "amount": 5,
      "investable": 3,
      "minimum": 3
    },
    {
      "name": "High Capacity Lens",
      "amount": 2,
      "investable": 6,
      "minimum": 0
    },
    {
      "name": "Steel",
      "amount": 3,
      "investable": 10,
      "minimum": 4
    }
  ]
};

/** Summed investFactor per stat, for every recipe above. */
export const INVESTMENT = {
  "ChainGun": {
    "fireRate": 0.3,
    "reach": 0.4,
    "damage": 0.4
  },
  "PointDefenseChainGun": {
    "fireRate": 0.3,
    "reach": 0.4,
    "damage": 0.4
  },
  "Bolter": {
    "fireRate": 1,
    "reach": 0.4,
    "damage": 0.4
  },
  "Laser": {
    "damage": 0.4,
    "reach": 1,
    "maxHeat": 0.75
  },
  "PointDefenseLaser": {
    "fireRate": 0.3,
    "damage": 0.4,
    "reach": 1
  },
  "PlasmaGun": {
    "damage": 0.4,
    "reach": 0.4,
    "maxHeat": 0.75
  },
  "Cannon": {
    "fireRate": 1,
    "damage": 0.6000000000000001,
    "reach": 0.4
  },
  "RocketLauncher": {
    "fireRate": 1,
    "damage": 0.4,
    "reach": 0.9
  },
  "RailGun": {
    "fireRate": 1,
    "damage": 0.6,
    "reach": 0.6
  },
  "RepairBeam": {
    "hullRepair": 0.4,
    "shieldRepair": 0.4,
    "reach": 0.75,
    "energyIncreasePerSecond": -0.5
  },
  "MiningLaser": {
    "damage": 0.075,
    "reach": 1
  },
  "SalvagingLaser": {
    "damage": 0.4,
    "reach": 1
  },
  "RawMiningLaser": {
    "damage": 0.075,
    "reach": 1
  },
  "RawSalvagingLaser": {
    "damage": 0.4,
    "reach": 1
  },
  "ForceGun": {
    "holdingForce": 0.4,
    "reach": 1
  },
  "TeslaGun": {
    "damage": 0.4,
    "reach": 0.3,
    "maxHeat": 0.75
  },
  "LightningGun": {
    "damage": 0.45,
    "reach": 0.2,
    "maxHeat": 0.75
  },
  "PulseCannon": {
    "fireRate": 0.3,
    "reach": 0.4,
    "damage": 0.4
  },
  "AntiFighter": {
    "fireRate": 0.3,
    "reach": 0.5,
    "damage": 0.6000000000000001
  },
  "HETRepairBeam": {
    "shieldRepair": 0.75,
    "reach": 0.75
  },
  "HETMiningLaser": {
    "reach": 2
  },
  "HETSalvagingLaser": {
    "reach": 2
  },
  "HETForceGun": {
    "otherForce": 1,
    "selfForce": 1,
    "reach": 2
  },
  "HETBolter": {
    "reach": 1.5,
    "damage": 0.3
  },
  "HETAntiFighter": {
    "reach": 1.5,
    "damage": 1.75
  },
  "HETRailGun": {
    "damage": 0.14,
    "reach": 0.2
  },
  "HETChainGun": {
    "damage": 0.7
  },
  "HETFlamethrower": {
    "damage": 0.45
  },
  "HETLaser": {
    "reach": 0.30000000000000004
  },
  "HETRepairDropper": {
    "hullRepair": 205,
    "reach": 1.5
  },
  "HETTopedoKiller": {
    "reach": 0.55
  },
  "HETPulseShotgun": {
    "damage": 0.7,
    "reach": 0.05
  },
  "HETSwarmMissiles": {
    "reach": 1.5,
    "damage": 0.25
  },
  "HETRefinementDropper": {},
  "HETRMHammerHead": {
    "damage": 0.07,
    "reach": 1
  },
  "HETRSHammerHead": {
    "damage": 0.07,
    "reach": 1
  },
  "HETGatlingPlasma": {
    "damage": 0.07
  },
  "HETCannon": {
    "damage": 0.75,
    "reach": 0.5
  },
  "HETInpulse": {},
  "HETTeslaGun": {
    "damage": 0.4,
    "otherForce": 1
  },
  "HETInterceptor": {
    "damage": 1.1,
    "reach": 0.5
  },
  "HETLRL40160": {
    "hullRepair": 0.75,
    "reach": 0.75
  },
  "HETPredatorCannon": {
    "damage": 0.9
  },
  "HETCrawler": {
    "damage": 0.45
  },
  "HETClusters": {
    "damage": 0.45,
    "reach": 0.25
  },
  "HETADST": {
    "damage": 0.9,
    "reach": 0.25
  },
  "HETLLTLT": {},
  "HETOphidian": {
    "damage": 0.07
  }
};

/** ArmedObjectPrice weights. HET's inventoryitemprice.lua overrides the base table. */
export const VALUE_WEIGHT = {
  "ChainGun": 0.75,
  "Bolter": 0.6,
  "PulseCannon": 0.75,
  "PointDefenseChainGun": 1,
  "PointDefenseLaser": 2,
  "AntiFighter": 10,
  "PlasmaGun": 1,
  "Laser": 1,
  "RocketLauncher": 0.5,
  "Cannon": 0.75,
  "RailGun": 1,
  "LightningGun": 0.65,
  "TeslaGun": 0.8,
  "RepairBeam": 3,
  "ForceGun": 1,
  "MiningLaser": 1,
  "RawMiningLaser": 0.25,
  "SalvagingLaser": 1,
  "RawSalvagingLaser": 0.45
};
export const RARITY_WEIGHT = {
  "MiningLaser": 0.5,
  "RawMiningLaser": 0.5,
  "ForceGun": 0.2,
  "PointDefenseChainGun": 0.2,
  "PointDefenseLaser": 0.2
};
export const REACH_WEIGHT = {
  "SalvagingLaser": 5,
  "RawSalvagingLaser": 5
};

/** turretfactory.lua: tax on manufacturing, waived at your own faction's factory. */
export const CREATION_TAX = 0.2;

/** The factory caps tech at 50 on purpose — 51/52 turrets are loot only. */
export const MAX_FACTORY_TECH = 50;
